language: ruby
rvm:
  - 2.4.3
services:
  - postgresql
before_script:
  - bundle install
  - psql -c 'create database bb_test;' -U postgres
script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec
test:
  adapter: postgresql
  database: bb_test