
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: bb_development

test:
  <<: *default
  database: bb_test

production:
  <<: *default
  database: bb_production
  username: bb
  password: <%= ENV['BB_DATABASE_PASSWORD'] %>
